### ISSUE TITLE
[JOSS Review] Source install v1.0.0rc4.dev6 error on OSX

### ISSUE THREAD

**Issue by gbouras13** [kdm9/Acanthophis#14]
Re https://github.com/openjournals/joss-reviews/issues/6062

After #13 , I instead proceeded with a source install instead of pip

i.e. 

```

mamba create -n someproject python snakemake pip natsort
mamba activate someproject
git clone https://github.com/kdm9/Acanthophis.git

cd Acanthophis 
pip install -e .
```

which worked 

```
Installing collected packages: acanthophis
Successfully installed acanthophis-1.0.0rc4.dev6
```

Then I tried to run `acanthophis-init`, which did not:

```
cd ..
acanthophis-init some_project
```

```
Traceback (most recent call last):
  File "/Users/a1667917/mambaforge/envs/someproject/bin/acanthophis-init", line 8, in <module>
    sys.exit(init())
             ^^^^^^
  File "/Users/a1667917/Documents/Reviews/acanthophis/Acanthophis/acanthophis/cmd.py", line 64, in init
    template_dir = acanthophis.get_resource("template/")
                   ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'acanthophis' has no attribute 'get_resource'
```

George

**Comment by kdm9** [comment]
Hi George, apologies, but I can't reproduce this in a fresh docker container. Could you please `pip install -U acanthophis` and confirm that this still happens in the latest version (which is now 0.3.0).

**Comment by kdm9** [comment]
Also, do I guess correctly that you're on OSX? I really doubt that will cause issues, but I have never tested this on an OSX machine, so there is a minor chance there is some strange bug lurking on OSX.

**Comment by kdm9** [comment]
@gbouras13 A thought: this could be due to poor interaction between installed pythons. Could you please check `which pip` (I think that works on osx, maybe `command -v pip`?). It should be a path under the active conda env, not e.g. /usr/bin/pip or some other dir, e.g. in homebrew.

This is an issue that would apply to all python packages, and is one of the rougher edges around python packaging.

**Comment by gbouras13** [comment]
Hi @kdm9 ,

Can confirm that pip is in the right place 

`/Users/a1667917/mambaforge/envs/acanthophis/bin/pip`

One thing - Have you considered putting acanthophis on bioconda? Then perhaps it might be slightly easier to install if this is an issue with pip vs conda.

George

**Comment by kdm9** [comment]
OK, I am genuinely unable to reproduce this on any system I try. This is troubling and I want to fix this though, as this should not be any users first experience of a program. Is there any other details or debugging you can do? As far as I can tell, I ran your exact commands below, so it should have identical behaviour if the issue is as simple as a missing function or import.

About conda: yes, I have a draft package in my channel, but it's linux only, and is slightly out of date. I'll update it quickly now, and then you should be able to `mamba install -c kdm801 acanthophis=0.3.1`.



```
docker run -it --rm condaforge/miniforge3

# within docker:
root@368cfb25bd0a:/# mamba create -n someproject -c bioconda -c conda-forge python snakemake pip natsort
<<<<SNIP LOGO>>>>>
Looking for: ['python', 'snakemake', 'pip', 'natsort']

conda-forge/linux-64                                        Using cache
conda-forge/noarch                                          Using cache
bioconda/noarch                                      5.1MB @   3.7MB/s  1.4s
bioconda/linux-64                                    5.3MB @   3.7MB/s  1.5s
Transaction

  Prefix: /opt/conda/envs/someproject

  Updating specs:

   - python
   - snakemake
   - pip
   - natsort


  Package                                      Version  Build                Channel                   Size
─────────────────────────────────────────────────────────────────────────────────────────────────────────────
  Install:
─────────────────────────────────────────────────────────────────────────────────────────────────────────────


  + natsort                                      8.4.0  pyhd8ed1ab_0         conda-forge/noarch        37kB
  + python                                      3.12.1  hab00c5b_1_cpython   conda-forge/linux-64      32MB
  + snakemake                                    8.2.1  hdfd78af_0           bioconda/noarch            9kB
  + snakemake-interface-common                  1.15.1  pyhdfd78af_0         bioconda/noarch           18kB
  + snakemake-interface-executor-plugins         8.2.0  pyhdfd78af_0         bioconda/noarch           22kB
  + snakemake-interface-storage-plugins          3.0.0  pyhdfd78af_0         bioconda/noarch           18kB
  + snakemake-minimal                            8.2.1  pyhdfd78af_0         bioconda/noarch          207kB
  
<<<SKIPPED A LOT OF PKGS ABOVE>>>
  Summary:

  Install: 121 packages

  Total download: 104MB


Confirm changes: [Y/n] 
 <<<<SKIP INSTALL LOG>>>>
Downloading and Extracting Packages

Preparing transaction: done
Verifying transaction: done
Executing transaction: done

To activate this environment, use

     $ mamba activate someproject

To deactivate an active environment, use

     $ mamba deactivate

(base) root@368cfb25bd0a:/Acanthophis# conda activate someproject
(someproject) root@368cfb25bd0a:/Acanthophis# pip install -e .
Obtaining file:///Acanthophis
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Preparing editable metadata (pyproject.toml) ... done
Requirement already satisfied: natsort in /opt/conda/envs/someproject/lib/python3.12/site-packages (from acanthophis==0.3.1.dev26) (8.4.0)
Requirement already satisfied: snakemake>=8 in /opt/conda/envs/someproject/lib/python3.12/site-packages (from acanthophis==0.3.1.dev26) (8.2.1)
<<<<<SKIP LOTS MORE "Requirement already satisfied:" >>>>
Building wheels for collected packages: acanthophis
  Building editable for acanthophis (pyproject.toml) ... done
  Created wheel for acanthophis: filename=acanthophis-0.3.1.dev26-0.editable-py2.py3-none-any.whl size=9818 sha256=06c58830d1490df1b2953ffa776e3862a8ed835b987d18a8cc6741af065045cb
  Stored in directory: /tmp/pip-ephem-wheel-cache.....
Successfully built acanthophis
Installing collected packages: acanthophis
Successfully installed acanthophis-0.3.1.dev26
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
(someproject) root@368cfb25bd0a:/Acanthophis# acanthophis-init some_project
cp -r /Acanthophis/acanthophis/template/ -> some_project? (WARNING: make sure you have git add'd all files as they will be overwritten)  [yN] y
(someproject) root@368cfb25bd0a:/Acanthophis#

```

**Comment by kdm9** [comment]
I just tried to reproduce this on a colleague's OSX laptop, and couldn't reproduce this there either. But, nor could I install several of the dependencies. I've added a note to the JOSS paper and to the readme that Acanthophis is only supported on Linux, because the underlying tools seem uninstallable on OSX, and therefore it's not exactly useful.
